version: '2'

services:
  mysql:
    image: mysql:5.7.18
    container_name: shopifine-mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: shopfine
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl
